### ISSUE TITLE
Common pairs

### ISSUE THREAD

**Issue by noxydev** [cryptoeax/arbbot#2] opened 2017-12-04 16:15 UTC
Hello,
Thank you for your good work !!!
I need your help.  I don't know if the bot works normally because it search opportunities on only 5 common pairs.
Can you help me ?

**Comment by cryptoeax** [comment] 2017-12-04 18:52
Why is that a problem?  The bot should work just fine with just 5 common pairs...

**Comment by remipaeta** [comment] 2017-12-05 09:37
I have 38 common pairs but I had the same problem.
I was forced to generate an address in each of the wallets in BITTREX.

**Comment by cryptoeax** [comment] 2017-12-05 20:24
Interesting...

I committed 5be9e07 which makes the current code for getting a deposit address from Bittrex more robust.  But I think the issue is that Bittrex's API doesn't return the wallets you haven't generated a deposit address for...

@rpcrypto Any chance you could please post the list of the common pairs you have which have a non-zero balance currently?  Also, which version of the bot are you testing?  Can you please run `git show` inside the directory of your git clone and post the sha1 of your copy?  I'm asking because I have recently modified the heuristics in `CoinManager.php` which controls which assets are held.  Thanks!

**Comment by cryptoeax** [comment] 2017-12-06 19:33
3eb2c72 should increase the number of the common pairs that the bot detects.  It makes the bot take pairs into account that it doesn't have a wallet for yet.  I'd appreciate if you would please test this change and let me know how it works for you.

**Comment by remipaeta** [comment] 2017-12-09 00:43
It works for me :-) !

**Comment by cryptoeax** [comment] 2017-12-09 03:16
> It works for me :-) !

Note that I have temporarily reverted this in bf56b9e.  This ended up reducing the efficiency of the bot because with all of the extra coins it started to check, the frequency at which it would check the actual profitable coins and potentially trade on those got dropped drastically.

Once #12 is fixed, this can be committed again with a heuristic based on the profitability model to add some weight to the profitable altcoins.  Since this issue is open I won't forget to actually do that...

**Comment by cryptoeax** [comment] 2017-12-30 07:40
I committed this again in 8f392a307a725774f7886451c25fce4ac82c5901.

**Closed as completed by cryptoeax** 2017-12-30 07:40 UTC
