### ISSUE TITLE
Wallet blank on WEB UI

### ISSUE THREAD

**Issue by remipaeta** [cryptoeax/arbbot#48] opened 2017-12-26 16:33 UTC
Hello @cryptoeax,
Since the latest commits, the wallets area is blank on the web ui.
I added an API from another exchange and it worked before.
Can you help me ?
I created a map file corresponding to the ID of the exchange.

**Comment by cryptoeax** [comment] 2017-12-27 17:56
Hmm, it's possible there was a bug in the latest code changes, but since I can't reproduce the bug I need some more information from you to fix it.

Can you please go and look at your nginx error logs and see if you have any recent errors there?  On Linux for example, it would be located in `/var/log/nginx/error.log`.  Refreshing the UI in your browser and then running  `tail /var/log/nginx/error.log` and pasting the output here should be enough.  Thanks!

**Comment by remipaeta** [comment] 2017-12-28 20:09
2017/12/28 21:07:01 [error] 19889#19889: *157518 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/arbbot/bot/xchange/Bleutrade
.php): failed to open stream: No such file or directory in /var/www/arbbot/bot/Exchange.php on line 39
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/arbbot/bot/xchange/Bleutrade
.php' (include_path='.:/usr/share/php') in /var/www/arbbot/bot/Exchange.php on line 39" while reading response header from upstream, client: 176.147.126.115, server: localhost...

It's exactly like this.

**Comment by remipaeta** [comment] 2017-12-28 20:10
I can share the Bleutrade file if you are interested @cryptoeax

**Comment by cryptoeax** [comment] 2017-12-28 20:47
> 2017/12/28 21:07:01 [error] 19889#19889: *157518 FastCGI sent in stderr: "PHP message: PHP Warning: require_once(/var/www/arbbot/bot/xchange/Bleutrade
> .php): failed to open stream: No such file or directory in /var/www/arbbot/bot/Exchange.php on line 39
> PHP message: PHP Fatal error: require_once(): Failed opening required '/var/www/arbbot/bot/xchange/Bleutrade
> .php' (include_path='.:/usr/share/php') in /var/www/arbbot/bot/Exchange.php on line 39" while reading response header from upstream, client: 176.147.126.115, server: localhost...
> 
> It's exactly like this.

The error says that you have deleted `bot/xchange/Bleutrade.php`, but you have forgotten to delete the corresponding `require_once` on line 39 of `bot/Exchange.php`.  :-)  I think you probably deleted Bluetrade.php by mistake?

> I can share the Bleutrade file if you are interested @cryptoeax

Yes, that would be awesome, thank you!

**Comment by remipaeta** [comment] 2017-12-28 22:14
Can you give me your mail address ?

**Comment by cryptoeax** [comment] 2017-12-28 23:44
I received the file.  Closing this issue now.  Thanks!

**Closed as completed by cryptoeax** 2017-12-28 23:44 UTC
