### ISSUE TITLE
"Timestamp for this request is outside of the recvWindow"

### ISSUE THREAD

**Issue by ericfraselle** [cryptoeax/arbbot#150] opened 2018-02-05 16:35 UTC
I received this error several time, even after restart and/or update time with ntp.

**Comment by OlegVic** [comment] 2018-02-05 17:17
have same error on BINANCE

**Comment by jjc6676** [comment] 2018-02-05 19:43
same

**Comment by ericfraselle** [comment] 2018-02-05 20:09
There is the same kind of bug on ccxt. I found a lot of reference with this error, ccxt and binance.
But I didn't find the solution.

**Comment by OlegVic** [comment] 2018-02-05 20:16
have 2 variants then create object (
`
$this->exchange = new $ccxtName( array(
      'enableRateLimit' => true,
    ) );
`
):
need add options:
1. ` 'recvWindow' => 5 * 1000, // 5 sec, binance default ` - better
2. ` 'adjustForTimeDifference' => false, // controls the adjustment logic upon instantiation ` - not safe

i made changes in CCXT file binance.php
`                'recvWindow' => 15 * 1000, // 5 sec, binance default `
Set 15 seconds! and now works for me!

**Comment by jjc6676** [comment] 2018-02-05 20:37
You added these lines to `bot/xchange/binance.php`
For clarity,
Can you tell me where you added them and exactly what you added?

**Comment by jjc6676** [comment] 2018-02-05 20:42
I found it

**Comment by jjc6676** [comment] 2018-02-05 20:46
Are you guys getting this one 
`Deposit Address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Memo:
[BITTREX] API error response: PAYMENTID_NOT_SUPPORTED`

The xx's are my deposit address replaced

**Comment by cryptoeax** [comment] 2018-02-07 15:10
> Are you guys getting this one
> Deposit Address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Memo: [BITTREX] API error response: PAYMENTID_NOT_SUPPORTED
> 
> The xx's are my deposit address replaced

That one was fixed by e53c15c154cd80b8d30096f4cfac51fe04d9792a, it was a recent regression.

About the other errors, I would appreciate if someone can provide some more detailed log.  A one line error message is hardly helpful.  For example, I am not sure which API call is throwing this error at the moment.  :-)

**Comment by cryptoeax** [comment] 2018-02-09 15:23
https://github.com/ccxt/ccxt/issues/936 explains the causes of this error.  This can be caused by time drifts between the machine arbbot is running on and the Binance servers.  In order to improve the situation it is recommended:

  * To run nptd.
  * To increase recvWindow.

**Closed as completed** 2018-02-09 15:27 UTC
